import { Inter, Varela_Round } from "next/font/google";

import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });
const valeraRound = Varela_Round({ subsets: ["latin"], weight: "400"})

export const metadata = {
  title: "Adrian Lara - Home Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${valeraRound.className} flex min-h-screen flex-col items-center justify-between`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
